config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  # rails engine for comment
  mount Commontator::Engine => '/commontator'

  # ai-indexing part 
  post 'ai_index', to: "ai_indexing#receive"
  get 'show_result', to: "ai_indexing#show_result"


  get 'listing' => 'listings#listing_interview', as: 'listing'
  get 'listing-inner' => 'listings#listing_inner', as: 'listing_inner'
  get 'listing-approval' => 'listings#listing_approval', as: 'approval_page'
  get 'applicants/index'
  get 'landings/index', as: 'landing'
  get '/newhome', to: 'landings#newhome', as: 'newhome'
  get '/pricing', to: 'landings#pricing', as: 'pricing'
  post 'landings/requestdemo', to: "landings#request_demo"
  put 'update_approval_status' => 'listings#update_approval_status', as: 'update_approval'
  get "build_profile", to: "users#build_profile", as: 'build_profile', :format => false
  post "build_profile_update", to: "users#update_profile", as: 'update_profile', :format => false
  put "become_interviewer", to: "users#become_interviewer", as: 'become_interviewer', :format => false
  put "become_applicant", to: "users#become_applicant", as: 'become_applicant', :format => false
  get "profile", to: "users#profile", as: 'user_profile', :format => false
  get "application_timeline", to: "users#application_timeline", as: 'user_timeline', :format => false
  get "dashboard/account", to: "users#account", as: 'user_account', :format => false
  post "dashboard/account", to: "users#account", as: 'user_account_put'
  get "dashboard/check_password", to: "users#check_password", as: 'check_password'
  get "dashboard/interviews", to: "users#interviews", as: 'user_interviews', :format => false
  get 'demo_login' , to: "users#user_demo_login", as: 'user_demo_login'
  get 'demo_in' , to: "users#trigger_login", as: 'trigger_login'
  get 'contact', to: "landings#contact", as: 'contact'
  get 'payment_test', to: "payment#payment_test", as: 'payment_test'
  get 'payment_test_url', to: "payment#payment_test_callback",  as: 'payment_test_callbadk'
  get 'payment_test_submit', to: "payment#payment_test_submit", as: 'payment_test_submit'

  put 'update_education', to: "users#update_education", as: 'update_education'
  put 'update_experience', to: "users#update_experience", as: 'update_experience'
  put 'update_skills', to: "users#update_skills", as: 'update_skills'
  put 'update_user_details', to: "users#update_user_details", as: 'update_user_details'
  get 'retrieve_education', to: "users#retrieve_education", as: 'retrieve_education'
  delete 'delete_education', to: "users#delete_education", as: 'delete_education'

  post "update_account_profile", to: "users#update_account_profile", as: "update_account_profile"
  post "update_account_skill", to: "users#update_account_skill", as: "update_account_skill"  

  get "check_if_user_exist", to: "users#check_if_user_exist", as: "check_if_user_exist"
  post "login_sign_up", to: "users#login_sign_up", as: "login_sign_up"

  # post request for applicant data
  post 'applicants/' => 'applicants#index'
  post 'applicants/question' => 'applicants#question'
  post 'applicants/submit_video' => 'applicants#submit_video'
  post 'applicants/upload_file' => 'applicants#upload_file'


  %w( validate_interview validate_email ).each do |action|
    get  action => 'applicants#'+action
  end

  get "check_subdomain", to: "companies#check_subdomain"

  # this is assigning device controllers for user(s)
  devise_for :users, controllers: {invitations: 'users/invitations', registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]


  # error handling routes, this will , pass the code to controller error and action show
  %w( 404 422 500 ).each do |code|
    get code, :to => "landings#errors", :code => code
  end



  # Nested Company Resources
  resources :companies do
    #post 'send_invite_mail', on: :collection
    #get "interview_reminder", to: "companies#interview_reminder"
    post "add_collaborators", to: "companies#add_collaborators"
    delete "remove_collaborator", to: "companies#remove_collaborator"
    put "transfer_ownership", to: "companies#transfer_ownership"
    get "edit_preview", to: "companies#edit_preview"
    post "edit_preview", to: "companies#edit_preview"
    get "all_interview", to: "companies#all_interview"
    get "preview", to: "companies#preview"
    get "card_preview", to: "companies#card_preview", as: 'card_preview'
    get "talent", to: "companies#search_talent", as: "talent"
    get "talent/:id", to: "companies#show_talent", as: "show_talent"
    get "organization_members", to: "companies#organization_members", as: "organization_members"

    resources :groups do
       get 'show_group_emails', on: :member
       resources :bulks do
          post 'import', on: :collection
      end
    end

    resources :interviews do
      post 'send_invite_mail', on: :collection
      get "reminder", to: "interviews#reminder"
      get "sms_reminder", to: "interviews#sms_reminder"
      get "double_reminder", to: "interviews#double_reminder"
      get "mass", to: "interviews#mass_notify"
      get "analytics", to: "interviews#analytics"
      get "single", to: "interviews#single_interview_submissions"
      get "returnTextFileApi", to: "interviews#returnTextFileApi"
      get "filtered_single_interview", to: "interviews#filtered_single_interview"
      put "change_status", to: "interviews#change_status"
      # get "shortlist", to: "interviews#shortlist"
      # get "reject", to: "interviews#reject"
      get "unfinish_submission", to: "interviews#unfinish_submission" 
      get "export_details", to: "submissions#export",  as: 'export_submissions'
      get "shortlist", to: "submissions#shortlist"
      get "reject", to: "submissions#reject"
    end

  end


  get 'users/auth/linkedin/callback', to: 'oauths#callback_linkedin', as: 'oauth_callback_linked'
  get 'users/auth/facebook/callback', to: 'oauths#callback'
  get 'users/auth/failure', to: 'oauths#failure', as: 'oauth_failure'
  # checking if the subdomain is available, if yes to to route
  # if not route back to rool url
  get '/' => 'applicants#index', :constraints => CustomDomainConstraint

  constraints(CustomDomainConstraint) do
     get '/' => 'applicants#index'
     get 'applicants/' => 'applicants#index'
     get 'applicants/:interview_token/' => 'applicants#index'

  end

  # You can have the root of your site routed with "root"
    root 'landings#index'

  #get 'users/auth/linkedin/callback' => 'users#createt'

# If you have the need for more deep customization,
# for instance to also allow "/sign_in" besides "/users/sign_in",
# all you need to do is to create your routes normally
# and wrap them in a devise_scope block in the router:
# This way, you tell Devise to use the scope :user when "/sign_in" is accessed. Notice devise_scope is also aliased as as in your router.


   devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    put    "update_notification"  => "users#update_notification"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end



# namespace and controller for api
namespace :api do
    namespace :v1 do
      get "token", to: "api#token"
      put "send_invitation", to: "api#send_invitation"

    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	include FriendlyId

	validates :name, presence: true
	belongs_to  :company
	has_many  :bulks, dependent: :destroy


	friendly_id :name, :use => :slugged 

    def should_generate_new_friendly_id?
    	 slug.nil? || name_changed? || new_record?
 	  end

    # Try building a slug based on the following fields in
  	# increasing order of specificity.
    def slug_candidates
    [
      :name,
      [:name, :auto_response]
    ]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout 'user_dashboard'
  before_action :authenticate_user!
  before_action :set_up_user
  before_action :set_company
  before_action :set_group , :except => [:new, :create, :index]


  def index
  	@groups = @company.groups
    @group_new = Group.new
  end

  def new
  	@group = Group.new
  end


  def show

  end




  def create
    	@group = Group.new(group_params)
       # @group.company_id = @company.id
       @group.company = @company

    	if @group.save
    		 redirect_to company_groups_path, notice: "The group #{@group.name} has been uploaded."
      else
    	   render "new"
      end
  end

  def destroy
    @group = Group.friendly.find(params[:id])
    @group.destroy
    redirect_to company_groups_path, notice: "The  contact group #{@group.name} has been deleted."
  end


  def show_group_emails
    contact = @group.bulks
    render :json => contact.as_json(:only => [:email])
  end


private
      def set_group
        @group = Group.friendly.find(params[:group_id] || params[:id])
        # check if company has permission to view the interview
        if !(@group.company_id == @company.id)
          redirect_to company_path
        end

    end

    def set_company
        @company = Company.friendly.find(params[:company_id] || params[:id])
        result = JointUserCompany.find_by(user_id: @user.id, company_id: @company.id)
        if result.nil?
           redirect_to user_dashboard_path
        end
    end

    def group_params
  	   params.require(:group).permit(:name, :auto_response)
  	end

    def set_up_user
        @user = current_user
        @notification = Notification.where(user_id: @user.id, read: 0)
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/index.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">

<!-- TODO Add Sidebar Panel -->
 <%= render partial: "companies/sidebar" %>
<div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>

    <div class="content">
    	<div class="container-fluid">
		 <div class="card box-shape">
		 	<!-- <div > -->
		 	<!--<% if !flash[:notice].blank? %>
						<div class="alert alert-info">
						<%= flash[:notice] %>
						</div>
					<% end %> -->
             <!-- </div> -->

        	<div class="content">
			    <div class="content table-responsive table-full-width">
			      <table  class="table table-striped">
					<thead>
					 <tr>
					 	<th>Name</th><th>Size</th><th>Modify</th><th></th>
					</tr>
					</thead>
					<tbody>
						<% @groups.each do |group|%>
					<tr>
						<td> <%=group.name%></td>
						<% @size = group.bulks.length %>
						<td> <%= @size %> Contact </td>
						<td> <%= link_to "Update", company_group_bulks_path(company_id:@company.slug, group_id:group.slug) %> </td>
						
						<td> 
							<%= link_to  "Delete", company_group_path(id: group.id), method: :delete, data: { confirm: "Are you sure you want to delete  #{group.name}?" } %>   
						</td>
					</tr>
					<% end %>
					</tbody>
				</table>
			    </div>	
				<hr>
					<%= form_for ([@company, @group_new]), html:{multipart:true} do |f| %>
					 <div class="row">
				    	<div class="form-group col-md-5" >
				    		<%= f.label :name %>
							<%=f.text_field :name, placeholder:"New group name", class: "form-control border-input" %>
					    </div>
				    	<div class="form-group col-md-5" >
				    		<%=f.label :auto_response %>
							<%=f.text_field :auto_response, placeholder:"(Optional) Auto response message " , class: "form-control border-input" %>
				    	</div>
				    	<div class="form-group col-md-2" >
				    		 <label>  &nbsp;  </label>
				    		<%=f.submit "Save", class: "btn btn-info btn-fill btn-wd"%>
				    	</div>	
						</div>
					<% end %>
				  <!-- <div class="header">
                    <%= link_to 'New group', new_company_group_path, class: "btn float-right box-shape" %>
                  </div> -->
				
				<br>
			   </div>
	</div>
	</div>
	</div> 

        
        </div>
    </div>

app/views/groups/new.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">
    
<!-- TODO Add Sidebar Panel -->
 <%= render partial: "companies/sidebar" %>
<div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                   
                    <div class="col-lg-12 col-md-12">
                        <div class="card">

                        	<% if !@group.errors.empty? %>
								<div class: alert "alert-error">
								<ul>

									<% @group.errors.full_messages.each do |msg|%>

								<li>
									<%= msg %>
								</li>
								<% end%>
								</ul>
								</div>
								<%end%>

							<div class: "well">
								<%= form_for ([@company, @group]), html:{multipart:true} do |f| %>
								<%= f.label :name %>
								<%=f.text_field :name%>
								<br/>
								<%=f.label :auto_response%>
								<%=f.text_field :auto_response%>
								<br/>
								<%=f.submit "Save", class: "btn btn-primary"%>
								<% end %>
							</div>
								                            
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/groups/show.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>
 	