config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  # rails engine for comment
  mount Commontator::Engine => '/commontator'

  # ai-indexing part 
  post 'ai_index', to: "ai_indexing#receive"
  get 'show_result', to: "ai_indexing#show_result"


  get 'listing' => 'listings#listing_interview', as: 'listing'
  get 'listing-inner' => 'listings#listing_inner', as: 'listing_inner'
  get 'listing-approval' => 'listings#listing_approval', as: 'approval_page'
  get 'applicants/index'
  get 'landings/index', as: 'landing'
  get '/newhome', to: 'landings#newhome', as: 'newhome'
  get '/pricing', to: 'landings#pricing', as: 'pricing'
  post 'landings/requestdemo', to: "landings#request_demo"
  put 'update_approval_status' => 'listings#update_approval_status', as: 'update_approval'
  get "build_profile", to: "users#build_profile", as: 'build_profile', :format => false
  post "build_profile_update", to: "users#update_profile", as: 'update_profile', :format => false
  put "become_interviewer", to: "users#become_interviewer", as: 'become_interviewer', :format => false
  put "become_applicant", to: "users#become_applicant", as: 'become_applicant', :format => false
  get "profile", to: "users#profile", as: 'user_profile', :format => false
  get "application_timeline", to: "users#application_timeline", as: 'user_timeline', :format => false
  get "dashboard/account", to: "users#account", as: 'user_account', :format => false
  post "dashboard/account", to: "users#account", as: 'user_account_put'
  get "dashboard/check_password", to: "users#check_password", as: 'check_password'
  get "dashboard/interviews", to: "users#interviews", as: 'user_interviews', :format => false
  get 'demo_login' , to: "users#user_demo_login", as: 'user_demo_login'
  get 'demo_in' , to: "users#trigger_login", as: 'trigger_login'
  get 'contact', to: "landings#contact", as: 'contact'
  get 'payment_test', to: "payment#payment_test", as: 'payment_test'
  get 'payment_test_url', to: "payment#payment_test_callback",  as: 'payment_test_callbadk'
  get 'payment_test_submit', to: "payment#payment_test_submit", as: 'payment_test_submit'

  put 'update_education', to: "users#update_education", as: 'update_education'
  put 'update_experience', to: "users#update_experience", as: 'update_experience'
  put 'update_skills', to: "users#update_skills", as: 'update_skills'
  put 'update_user_details', to: "users#update_user_details", as: 'update_user_details'
  get 'retrieve_education', to: "users#retrieve_education", as: 'retrieve_education'
  delete 'delete_education', to: "users#delete_education", as: 'delete_education'

  post "update_account_profile", to: "users#update_account_profile", as: "update_account_profile"
  post "update_account_skill", to: "users#update_account_skill", as: "update_account_skill"  

  get "check_if_user_exist", to: "users#check_if_user_exist", as: "check_if_user_exist"
  post "login_sign_up", to: "users#login_sign_up", as: "login_sign_up"

  # post request for applicant data
  post 'applicants/' => 'applicants#index'
  post 'applicants/question' => 'applicants#question'
  post 'applicants/submit_video' => 'applicants#submit_video'
  post 'applicants/upload_file' => 'applicants#upload_file'


  %w( validate_interview validate_email ).each do |action|
    get  action => 'applicants#'+action
  end

  get "check_subdomain", to: "companies#check_subdomain"

  # this is assigning device controllers for user(s)
  devise_for :users, controllers: {invitations: 'users/invitations', registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]


  # error handling routes, this will , pass the code to controller error and action show
  %w( 404 422 500 ).each do |code|
    get code, :to => "landings#errors", :code => code
  end



  # Nested Company Resources
  resources :companies do
    #post 'send_invite_mail', on: :collection
    #get "interview_reminder", to: "companies#interview_reminder"
    post "add_collaborators", to: "companies#add_collaborators"
    delete "remove_collaborator", to: "companies#remove_collaborator"
    put "transfer_ownership", to: "companies#transfer_ownership"
    get "edit_preview", to: "companies#edit_preview"
    post "edit_preview", to: "companies#edit_preview"
    get "all_interview", to: "companies#all_interview"
    get "preview", to: "companies#preview"
    get "card_preview", to: "companies#card_preview", as: 'card_preview'
    get "talent", to: "companies#search_talent", as: "talent"
    get "talent/:id", to: "companies#show_talent", as: "show_talent"
    get "organization_members", to: "companies#organization_members", as: "organization_members"

    resources :groups do
       get 'show_group_emails', on: :member
       resources :bulks do
          post 'import', on: :collection
      end
    end

    resources :interviews do
      post 'send_invite_mail', on: :collection
      get "reminder", to: "interviews#reminder"
      get "sms_reminder", to: "interviews#sms_reminder"
      get "double_reminder", to: "interviews#double_reminder"
      get "mass", to: "interviews#mass_notify"
      get "analytics", to: "interviews#analytics"
      get "single", to: "interviews#single_interview_submissions"
      get "returnTextFileApi", to: "interviews#returnTextFileApi"
      get "filtered_single_interview", to: "interviews#filtered_single_interview"
      put "change_status", to: "interviews#change_status"
      # get "shortlist", to: "interviews#shortlist"
      # get "reject", to: "interviews#reject"
      get "unfinish_submission", to: "interviews#unfinish_submission" 
      get "export_details", to: "submissions#export",  as: 'export_submissions'
      get "shortlist", to: "submissions#shortlist"
      get "reject", to: "submissions#reject"
    end

  end


  get 'users/auth/linkedin/callback', to: 'oauths#callback_linkedin', as: 'oauth_callback_linked'
  get 'users/auth/facebook/callback', to: 'oauths#callback'
  get 'users/auth/failure', to: 'oauths#failure', as: 'oauth_failure'
  # checking if the subdomain is available, if yes to to route
  # if not route back to rool url
  get '/' => 'applicants#index', :constraints => CustomDomainConstraint

  constraints(CustomDomainConstraint) do
     get '/' => 'applicants#index'
     get 'applicants/' => 'applicants#index'
     get 'applicants/:interview_token/' => 'applicants#index'

  end

  # You can have the root of your site routed with "root"
    root 'landings#index'

  #get 'users/auth/linkedin/callback' => 'users#createt'

# If you have the need for more deep customization,
# for instance to also allow "/sign_in" besides "/users/sign_in",
# all you need to do is to create your routes normally
# and wrap them in a devise_scope block in the router:
# This way, you tell Devise to use the scope :user when "/sign_in" is accessed. Notice devise_scope is also aliased as as in your router.


   devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    put    "update_notification"  => "users#update_notification"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end



# namespace and controller for api
namespace :api do
    namespace :v1 do
      get "token", to: "api#token"
      put "send_invitation", to: "api#send_invitation"

    end
  end

end

app/models/user.rb
require 'slack-notifier'
class User < ActiveRecord::Base
    # before_save :capitalize_first_character
    has_many :identities
	has_many :notifications
	has_many :joint_user_companies
	has_many :companies, :through => :joint_user_companies
    has_many :submissions
    mount_uploader :a_dp, ADpUploader
    mount_uploader :a_cv, ACvUploader

     after_create  :send_slack_notification
     def send_welcome_mail
        InterviewMailer.welcome_email(self).deliver
     end

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :invitable, :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :trackable, :validatable, :omniauthable

    # allow user to be able to comment
    acts_as_commontator

   #this will allow user to be able to rate
   ratyrate_rater



   # def capitalize_first_character
   #    self.name.split.map(&:capitalize).join(' ')
   # end
   def self.search_category

   end



   def send_slack_notification
    if Rails.env.production?
        # notifier = Slack::Notifier.new "https://hooks.slack.com/services/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", channel: '#notification', username: 'signup'
        # notifier.ping "New Signup by " + self.name + " email: " + self.email
    end
   end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/invitations_controller.rb
#  added by muyide ibukun, to change the behaviour of invitable controller
class Users::InvitationsController < Devise::InvitationsController
  layout 'signin'
  skip_filter :require_no_authentication, :only => :edit
  before_action :devise_configure_permitted_parameters, if: :devise_controller?
  

  protected

    def devise_configure_permitted_parameters
      sign_out current_user if user_signed_in?
      devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  #def linkedin
    #raise request.env["omniauth.auth"]
    # @user = User.find_for_linkedin_oauth(request.env["omniauth.auth"])
    #   if @user.persisted?
    #     redirect_to root_path, :event => :authentication
    #     # sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    #     #  set_flash_message(:notice, :success, :kind => "LinkedIn") if is_navigational_format?
    #     else
    #       session["devise.linkedin_data"] = request.env["omniauth.auth"]
    #       redirect_to root_path
    #     end
  #end



   #raise request.env["omniauth.auth"]
  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'signin'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
layout 'signin'
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super

  end

  # GET /resource/edit
  def edit
    @user = current_user
    @notification = Notification.where(user_id: @user.id, read: 0)
    render :layout => 'user_dashboard'
    # super
  end

  # PUT /resource
  def update
    @user = current_user
    @notification = Notification.where(user_id: @user.id, read: 0)
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :telephone])
    
    
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :name,
      :telephone,
      :a_qualification,
      :a_cv,
      :a_experience,
      :a_gender,
      :a_dp,
      :a_city,
      :a_address,
      :a_country
    ])
  end


  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_profile_path
  end


  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
layout 'landing'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
      if params[:intereview_token]
      elsif !session[:return_to].nil?
        session[:return_to]
      elsif user_signed_in? && current_user.status == 1
          dashboard_session
      elsif user_signed_in? && current_user.status == 0
         user_timeline_path
      else
        user_profile_path
      end
  end

  def dashboard_session
    user = current_user
    if user.last_company.nil?
      company_path(user.companies.first)
    elsif
      company = Company.friendly.find(user.last_company)
      company_path(company)
    else
     new_company_path
    end
  end




end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_applicant_sidebar.html.erb
<div class="sidebar-wrapper">
            <div class="logo align">
                  <%= image_tag('dqlg.png') %>
             </div>


            <ul class="nav">
                <br>
                <li  class="<%= (params[:c] == "1") ? "active": "" %>">
                     <a href="<%= user_account_path(c:"1") %>">
                        <i class="ti-user"></i>
                        <p>Profile</p>
                     </a>
                </li>

                <li  class="<%= (params[:c] == "2") ? "active": "" %>">
                    <a href="<%= user_timeline_path(c:"2") %>">
                        <i class="ti-folder"></i>
                        <p>Applications</p>
                   </a>
                </li>

                <li  class="<%= (params[:c] == "3") ? "active": "" %>" >
                    <a href="<%= user_interviews_path(c:"3") %>">
                        <i class="ti-search"></i>
                        <p>Interviews</p>
                   </a>
                </li>

            </ul>
    	</div>
    </div>

app/views/users/_footer.html.erb
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>

                <li>
                    <a href="#">
                        About us
                    </a>
                </li>
                <li>
                    <a href="#">
                        Terms
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script>,  <%= link_to 'Dropque', root_path %>
        </div>
    </div>
</footer>

app/views/users/_navbar.html.erb
<nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar bar1"></span>
                      <span class="icon-bar bar2"></span>
                      <span class="icon-bar bar3"></span>
                    </button>
                    <% if @company.nil? and @logo_off.nil? %>
                       <%= image_tag('dqlg.png', style:"height: 65px;" )%>
                    <% end %>
                </div>
                <div class="collapse navbar-collapse">
                  <% if !@interview.nil? %>
                    <a class="navbar-brand" href="#"> <%= truncate( @interview.title, :length => 50) %> </a>
                  <% end %>
                    <ul class="nav navbar-nav navbar-right">

          <% if !@company.nil? %>
            <li class="dropdown">
              <%# <% if @user.companies.length == 1 %1> %>
              <%#   <a href="<%= new_company_path %1>" style="border: 1px solid; border-radius: 24px;"> %>
              <%#        <p>New Organisation</p> %>
              <%#        <i class="ti-plus"></i> %>
              <%#   </a> %>
              <%#   <% else %1> %>
              <%#   <li class="dropdown"> %>
              <%#       <a href="#" class="dropdown-toggle" data-toggle="dropdown"> %>
              <%#            <p>Organisations</p> %>
              <%#            <i class="ti-menu-alt"></i> %>
              <%#           <b class="caret"></b> %>
              <%#       </a> %>
              <%#       <ul class="dropdown-menu"> %>
              <%#          <li> %>
              <%#             <a href="<%= new_company_path %1>" class="text-center" style="    background-color: #ccc;"> %>
              <%#                     Add New <i class="ti-plus"></i> %>
              <%#             </a> %>

              <%#          </li> %>
              <%#         <% @user.companies.each do | company | %1> %>
              <%#          <li> %>
              <%#                   <a href="<%= company_path(company, from_notification:1) %1>"> %>
              <%#                      <%= company.name %1> %>
              <%#                   </a> %>
              <%#         </li> %>
              <%#         <% end %1> %>
              <%#       </ul> %>
              <%#   </li> %>
              <%# <% end %1> %>
            </li>
          <% end %>

                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>Notifications</p>
                                    <i class="ti-bell"></i>
                                    <% if (@notification.length > 0) %>
                                       <span class="notification-bubble" id="notification-number">
                                            <%= @notification.length %>
                                       </span>
                                    <% end %>
                              </a>
                              <ul class="dropdown-menu">
                               <% @notification.each do |noti| %>
                                  <li>
                                       <a class="notificationa">
                                        <div class="card notification" >
                                            <div class="content">

                                                 <btn class='btn float-right close-notification' notification-id= "<%= noti.id %>">
                                                  <i class='ti-close'></i>
                                                </btn>

                                                   <div class="author">
                                                    <%= image_tag('dummy.png', class:"avatar small", alt:"Thumb") %>
                                                     <% if noti.type_notification == 1 %>
                                                        <span itemprop="author"> Interview Completed </span>
                                                    <% elsif noti.type_notification == 2 %>
                                                        <span itemprop="author"> New Company Invite </span>
                                                    <% elsif noti.type_notification == 3 %>
                                                         <span itemprop="author"> New Message </span>
                                                    <% elsif noti.type_notification == 4 %>
                                                         <span itemprop="author"> Removed From Company </span>
                                                    <% elsif noti.type_notification == 5 %>
                                                         <span itemprop="author"> Ownership Transfer </span>
                                                    <% end %>

                                                   </div>
                                                   <div class="clearfix"><%= noti.message %></div>

                                            </div>
                                        </div>
                                        </a>
                                  </li>
                                  <% end %>

                              </ul>
                        </li>

                        <% if !@company.nil? %>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <p><%= @company.name %></p>
                                <i class="ti-settings"></i>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                   <%= link_to edit_company_path(params[:company_id ] || params[:id ] ) do %> Settings <% end %>
                                </li>
                                <li>
                                   <%= link_to company_groups_path(params[:company_id ] || params[:id ] ) do %> Contact Groups <% end %>
                                </li>
                                 <li>
                                   <%= link_to company_preview_path(params[:company_id ] || params[:id ] ) do %> Preview page <% end %>
                                </li>
                            </ul>
                        </li>
                        <% end %>

                        <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                             <p><%= @user.name.split(" ")[0] %></p>
                             <i class="ti-user"></i>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <% if @user.status == 1  and @profile_page != true %>
                                <li><%= link_to "Applicant's view", user_account_path %></li>
                            <% else %>
                                <% if @user.companies.nil?  ||  @unique_to_p == false %>
                                    <li><%= link_to "Organization view", new_company_path %></li>
                                <% elsif !@user.companies.nil? and @user.last_company.nil? %>
                               <li><%= link_to "Organization view", company_path(Company.friendly.find(@user.companies.first)) %></li>
                                 <% else !@user.companies.nil? and !@user.last_company.nil? %>
                                <li><%= link_to "Organization view", company_path(Company.friendly.find(@user.last_company)) %></li>
                                <% end %>
                            <% end %>

                           <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                        </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

app/views/users/_talent_sidebar.html.erb
<div class="sidebar-wrapper">
            <div class="logo align">
                  <%= image_tag('dqlg.png') %>
             </div>


            <ul class="nav">
                <br>
                <li  class="<%= (params[:c] == "1") ? "active": "" %>">
                     <a href="<%= user_account_path(c:"1") %>">
                        <i class="ti-user"></i>
                        <p>Profile</p>
                     </a>
                </li>

                <li  class="<%= (params[:c] == "2") ? "active": "" %>">
                    <a href="<%= user_timeline_path(c:"2") %>">
                        <i class="ti-folder"></i>
                        <p>Applications</p>
                   </a>
                </li>

                <li  class="<%= (params[:c] == "3") ? "active": "" %>" >
                    <a href="<%= user_interviews_path(c:"3") %>">
                        <i class="ti-search"></i>
                        <p>Interviews</p>
                   </a>
                </li>

            </ul>
    	</div>
    </div>

app/views/users/_when_empty.html.erb
<div class="row">

    <div class="col-lg-12 col-md-12">
        <div>

        <div class="row sharing-area text-center">
            <br> <br> <br> <br>
            <h5>You don't belong to an organization yet, create one now</h5>



             <%= link_to new_company_path do %>
                <button  type="button" class="btn btn-raised btn-twitter">New Organization</button>

               <br><br> <br>
            <% end %>
        </div>
        </div>
    </div>
</div>
    

app/views/users/_when_empty_applications.html.erb
<div class="row">

    <div class="col-lg-12 col-md-12">
        <div>

        <div class="row sharing-area text-center">
            <br> <br> <br> 
            <h5>You have not taken any interview yet,  Search for available interview(s)</h5>



             <%= link_to listing_path do %>
                <button  type="button" class="btn btn-raised btn-twitter">Search for available interivew</button>

               <br><br> <br>
            <% end %>
        </div>
        </div>
    </div>
</div>
    

app/views/users/profile.html.erb
<div class="wrapper">
     
    <div class="main-panel expand">
        <!-- TODO Add Footer Partial -->
        <%= render partial: "users/navbar" %>


        
        <!--   Big container   -->
        <div class="container">
            <div class="container-fluid">
        
              

                         <br><br>
                        <div class="card wizard-card" id="wizardProfile">
                                <div class="wizard-header text-center">
                                    <h3 class="wizard-title">Enter As</h3>
                                </div>
                                <div class="wizard-navigation">
                                   
                                    <ul>
                                     <li>
                                            <a href="#account" data-toggle="tab"></a>
                                      </li>                  
                                    </ul>
                                </div>
                                <div class="tab-content">
                                    
                                    <div class="tab-pane" id="account">
                                        <div class="row">
                                            <div class="col-sm-8 col-sm-offset-2">
                                                <div class="col-sm-6">
                                                    <%= link_to build_profile_path do %>
                                                    <div class="choice" data-toggle="wizard-checkbox">
                                                        <input type="checkbox"  value="Code">
                                                        <div class="card card-checkboxes card-hover-effect" style="color: #e74c3c">
                                                            <i class="ti-id-badge"></i>
                                                            <p>Applicant</p>
                                                        </div>
                                                    </div>
                                                    <% end %>
                                                </div>
                                                <div class="col-sm-6">
                                                     <%= link_to become_interviewer_path , method: :put do %>
                                                    <div class="choice" data-toggle="wizard-checkbox" >
                                                        <input type="checkbox"  value="Develop">
                                                        <div class="card card-checkboxes card-hover-effect" style="color:#9b59b6">
                                                            <i class="ti-user"></i>
                                                            <p>Interviewer</p>
                                                        </div>
                                                    </div>
                                                    <% end %>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                      
                        </div>
                    <!-- </div> wizard container -->
              
            <!-- end row -->
         </div> <!-- end container fluid -->
        </div> <!--  big container -->



</div>
</div>