config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  # rails engine for comment
  mount Commontator::Engine => '/commontator'

  # ai-indexing part 
  post 'ai_index', to: "ai_indexing#receive"
  get 'show_result', to: "ai_indexing#show_result"


  get 'listing' => 'listings#listing_interview', as: 'listing'
  get 'listing-inner' => 'listings#listing_inner', as: 'listing_inner'
  get 'listing-approval' => 'listings#listing_approval', as: 'approval_page'
  get 'applicants/index'
  get 'landings/index', as: 'landing'
  get '/newhome', to: 'landings#newhome', as: 'newhome'
  get '/pricing', to: 'landings#pricing', as: 'pricing'
  post 'landings/requestdemo', to: "landings#request_demo"
  put 'update_approval_status' => 'listings#update_approval_status', as: 'update_approval'
  get "build_profile", to: "users#build_profile", as: 'build_profile', :format => false
  post "build_profile_update", to: "users#update_profile", as: 'update_profile', :format => false
  put "become_interviewer", to: "users#become_interviewer", as: 'become_interviewer', :format => false
  put "become_applicant", to: "users#become_applicant", as: 'become_applicant', :format => false
  get "profile", to: "users#profile", as: 'user_profile', :format => false
  get "application_timeline", to: "users#application_timeline", as: 'user_timeline', :format => false
  get "dashboard/account", to: "users#account", as: 'user_account', :format => false
  post "dashboard/account", to: "users#account", as: 'user_account_put'
  get "dashboard/check_password", to: "users#check_password", as: 'check_password'
  get "dashboard/interviews", to: "users#interviews", as: 'user_interviews', :format => false
  get 'demo_login' , to: "users#user_demo_login", as: 'user_demo_login'
  get 'demo_in' , to: "users#trigger_login", as: 'trigger_login'
  get 'contact', to: "landings#contact", as: 'contact'
  get 'payment_test', to: "payment#payment_test", as: 'payment_test'
  get 'payment_test_url', to: "payment#payment_test_callback",  as: 'payment_test_callbadk'
  get 'payment_test_submit', to: "payment#payment_test_submit", as: 'payment_test_submit'

  put 'update_education', to: "users#update_education", as: 'update_education'
  put 'update_experience', to: "users#update_experience", as: 'update_experience'
  put 'update_skills', to: "users#update_skills", as: 'update_skills'
  put 'update_user_details', to: "users#update_user_details", as: 'update_user_details'
  get 'retrieve_education', to: "users#retrieve_education", as: 'retrieve_education'
  delete 'delete_education', to: "users#delete_education", as: 'delete_education'

  post "update_account_profile", to: "users#update_account_profile", as: "update_account_profile"
  post "update_account_skill", to: "users#update_account_skill", as: "update_account_skill"  

  get "check_if_user_exist", to: "users#check_if_user_exist", as: "check_if_user_exist"
  post "login_sign_up", to: "users#login_sign_up", as: "login_sign_up"

  # post request for applicant data
  post 'applicants/' => 'applicants#index'
  post 'applicants/question' => 'applicants#question'
  post 'applicants/submit_video' => 'applicants#submit_video'
  post 'applicants/upload_file' => 'applicants#upload_file'


  %w( validate_interview validate_email ).each do |action|
    get  action => 'applicants#'+action
  end

  get "check_subdomain", to: "companies#check_subdomain"

  # this is assigning device controllers for user(s)
  devise_for :users, controllers: {invitations: 'users/invitations', registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]


  # error handling routes, this will , pass the code to controller error and action show
  %w( 404 422 500 ).each do |code|
    get code, :to => "landings#errors", :code => code
  end



  # Nested Company Resources
  resources :companies do
    #post 'send_invite_mail', on: :collection
    #get "interview_reminder", to: "companies#interview_reminder"
    post "add_collaborators", to: "companies#add_collaborators"
    delete "remove_collaborator", to: "companies#remove_collaborator"
    put "transfer_ownership", to: "companies#transfer_ownership"
    get "edit_preview", to: "companies#edit_preview"
    post "edit_preview", to: "companies#edit_preview"
    get "all_interview", to: "companies#all_interview"
    get "preview", to: "companies#preview"
    get "card_preview", to: "companies#card_preview", as: 'card_preview'
    get "talent", to: "companies#search_talent", as: "talent"
    get "talent/:id", to: "companies#show_talent", as: "show_talent"
    get "organization_members", to: "companies#organization_members", as: "organization_members"

    resources :groups do
       get 'show_group_emails', on: :member
       resources :bulks do
          post 'import', on: :collection
      end
    end

    resources :interviews do
      post 'send_invite_mail', on: :collection
      get "reminder", to: "interviews#reminder"
      get "sms_reminder", to: "interviews#sms_reminder"
      get "double_reminder", to: "interviews#double_reminder"
      get "mass", to: "interviews#mass_notify"
      get "analytics", to: "interviews#analytics"
      get "single", to: "interviews#single_interview_submissions"
      get "returnTextFileApi", to: "interviews#returnTextFileApi"
      get "filtered_single_interview", to: "interviews#filtered_single_interview"
      put "change_status", to: "interviews#change_status"
      # get "shortlist", to: "interviews#shortlist"
      # get "reject", to: "interviews#reject"
      get "unfinish_submission", to: "interviews#unfinish_submission" 
      get "export_details", to: "submissions#export",  as: 'export_submissions'
      get "shortlist", to: "submissions#shortlist"
      get "reject", to: "submissions#reject"
    end

  end


  get 'users/auth/linkedin/callback', to: 'oauths#callback_linkedin', as: 'oauth_callback_linked'
  get 'users/auth/facebook/callback', to: 'oauths#callback'
  get 'users/auth/failure', to: 'oauths#failure', as: 'oauth_failure'
  # checking if the subdomain is available, if yes to to route
  # if not route back to rool url
  get '/' => 'applicants#index', :constraints => CustomDomainConstraint

  constraints(CustomDomainConstraint) do
     get '/' => 'applicants#index'
     get 'applicants/' => 'applicants#index'
     get 'applicants/:interview_token/' => 'applicants#index'

  end

  # You can have the root of your site routed with "root"
    root 'landings#index'

  #get 'users/auth/linkedin/callback' => 'users#createt'

# If you have the need for more deep customization,
# for instance to also allow "/sign_in" besides "/users/sign_in",
# all you need to do is to create your routes normally
# and wrap them in a devise_scope block in the router:
# This way, you tell Devise to use the scope :user when "/sign_in" is accessed. Notice devise_scope is also aliased as as in your router.


   devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    put    "update_notification"  => "users#update_notification"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end



# namespace and controller for api
namespace :api do
    namespace :v1 do
      get "token", to: "api#token"
      put "send_invitation", to: "api#send_invitation"

    end
  end

end

app/models/bulk.rb
require 'roo'
class Bulk < ActiveRecord::Base
    belongs_to :group
    attr_accessible :name, :email, :telephone
    # cattr_accessor :current


    def self.fetch(file)
       ex = Excel.new(file.path, nil, :ignore)
       ex.default_sheet = ex.sheets[1]
       3.upto(1000) do |line|
       name = ex.cell(line,’A’)
       email = ex.cell(line,’B’)
       telephone = ex.cell(line,’C’)
       @bulk = Bulk.create(:name => name,:email => email,:telephone => telephone)
      end
   end
   def self.import(file)
        spreadsheet = open_spreadsheet(file)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        bulk = find_by_id(row["id"]) || new
        bulk.attributes = row.to_hash.slice(*accessible_attributes)
        bulk.group_id = $grou
        bulk.save!
      end
    end

     def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when ".csv" then Roo::CSV.new(file.path)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xml" then Roo::Excel2003XML.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end


end

app/controllers/bulks_controller.rb
class BulksController < ApplicationController
  layout 'user_dashboard'
  before_action :authenticate_user!
  before_filter :set_up_user
  before_action :set_company
  before_action :set_group
  before_action :set_bulk, only: [:show, :edit, :update, :destroy]
  

  def index
      @bulks = @group.bulks
      # @count = @bulk.length
 end


  def show

  end

  def new
    @bulk = Bulk.new
  end

  def edit

  end


  def create
    @bulk = Bulk.new(bulk_params)
    @bulk.group = @group
    respond_to do |format|
      if @bulk.save
        format.html { redirect_to company_group_bulks_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @bulk }
      else
        format.html { render :new }
        format.json { render json: @bulk.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @bulk.update(bulk_params)
        format.html { redirect_to company_group_bulks_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulk }
      else
        format.html { render :edit }
        format.json { render json: @bulk.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @bulk = Bulk.find(params[:id])
    @bulk.destroy
    respond_to do |format|
      format.html { redirect_to company_group_bulks_url, notice: "#{@bulk.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def import
   Bulk.import(params[:file])
    # bulk.group_id = @group.id
   redirect_to company_group_bulks_path, notice: "Contacts Successfully Uploaded"
  end

  def fetch
   Bulk.fetch(params[:file])
   redirect_to bulks_path, notice: "Contacts Successfully Uploaded"
  end

  private
  def set_up_user
      @user = current_user
      @notification = Notification.where(user_id: @user.id, read: 0)
  end


  # check if the group has permission to access the bulk file
  def set_bulk
    @bulk = Bulk.find(params[:id])
    if !(@bulk.group_id == @group.id)
      redirect_to company_group_bulks_path
    end
  end

  #  check if the company has permission to access the group
  def set_group
    @group = Group.friendly.find(params[:group_id] || params[:id])
    $grou = @group.id
    # check if company has permission to view the group
    if !(@group.company_id == @company.id)
      redirect_to company_path(@company.slug)
    end
  end

  # check if the user has permission to access the company
  def set_company
      @company = Company.friendly.find(params[:company_id] || params[:id])
      result = JointUserCompany.find_by(user_id: @user.id, company_id: @company.id)
      if result.nil?
         redirect_to user_dashboard_path
      end
  end


    def bulk_params
      params.require(:bulk).permit(:name, :email, :telephone)
    end
end

app/helpers/bulks_helper.rb
module BulksHelper
end

app/views/bulks/_form.html.erb
<%= form_for(@bulk, url: company_group_bulks_path) do |f| %>
  <% if @bulk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bulk.errors.count, "error") %> prohibited this bulk from being saved:</h2>

      <ul>
      <% @bulk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit  :update%>
  </div>
<% end %>

app/views/bulks/edit.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">
    
<!-- TODO Add Sidebar Panel -->
 <%= render partial: "companies/sidebar" %>
<div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                   
                    <div class="col-lg-12 col-md-12">
                        <div class="card">
                            
                            <div class="content">
                                
                               

                               <h4>Edit Contact</h4>
<%= form_for(@bulk, url: {action: 'update'}) do |f| %>

<%= render 'form', f: f %>
<%end%>


<%= link_to 'Back', company_group_bulks_path %>




                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/bulks/index.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">
    
<!-- TODO Add Sidebar Panel -->
 <%= render partial: "companies/sidebar" %>
<div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="card box-shape">
                          <div class="header">
                            <%= link_to 'Add contact', new_company_group_bulk_path, class: "btn float-right box-shape" %>
                             <h5><%= @group.name.capitalize %></h5>
                          </div>

                    <div class="content">

                            <% if !flash[:notice].blank? %>
                              <div class="alert alert-info">
                              <%= flash[:notice] %>
                              </div>
                            <% end %>
                           <!--  <center>
                              <strong><h3><%= @group.name %></h3></strong>
                            </center> -->
                      <div>
                        <table  class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                  <th>Name</th>
                                  <th>Email</th>
                                  <th>Telephone</th>
                                  <th colspan="2"></th>
                                </tr>
                                <% @bulks.each do |bulk| %>
                                  <tr>
                                    <td><%= bulk.name %></td>
                                    <td><%= bulk.email %></td>
                                    <td><%= bulk.telephone %></td>
                                    <td><%= link_to 'Modify', edit_company_group_bulk_path(id: bulk.id) %></td>
                                    <td><%= link_to 'Delete', company_group_bulk_path(id: bulk.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </tr>
                                <% end %>
                              </tbody>
                        </table>
                      </div>

                <hr>
                <div class="header text-center">
                  <h5> Add Bulk Contact</h5>
                </div>
                  <%=form_tag import_company_group_bulks_path, multipart: true do %>
                    <label for="file-upload" class="btn custom-upload">
                      <%= file_field_tag :file, id:"file-upload" %>
                      Attach bulk file
                    </label>
                    <div class="text-center" >File should be one of Excel(xls, xlsx), Text(csv, txt)and Xml files</div>
                    <br>
                    <div class="text-center">
                       <%= submit_tag "Upload Contacts", class: "btn btn-info btn-fill btn-wd" %>
                    </div>
                    <br><br>
                  <% end %>

                   <!-- <div class="row">
                      <div class="col-md-12">
                          <div class="form-group">
                              <label for="file-upload" class="btn custom-upload">
                                  <input id="file-upload" type="file" name="logo">
                                 Organization Logo
                              </label>
                              <div class="text-center"><label>Transparent 330 X 80 pixels </label></div>
                          </div>
                      </div>
                  </div> -->


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/bulks/new.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">
    
<!-- TODO Add Sidebar Panel -->
 <%= render partial: "companies/sidebar" %>
<div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                   
                    <div class="col-lg-12 col-md-12">
                        <div class="card">
                            
                            <div class="content">

                            	
					<h1>New Contact</h1>

					<%= render 'form' %>

					<%= link_to 'Back', company_group_bulks_path %>

                                




                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/bulks/show.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">
    
<!-- TODO Add Sidebar Panel -->
 <%= render partial: "companies/sidebar" %>
<div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                   
                    <div class="col-lg-12 col-md-12">
                        <div class="card">
                            
                            <h1>Groups#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>


                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>