config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  post '/rate' => 'rater#create', :as => 'rate'
  # rails engine for comment
  mount Commontator::Engine => '/commontator'

  # ai-indexing part 
  post 'ai_index', to: "ai_indexing#receive"
  get 'show_result', to: "ai_indexing#show_result"


  get 'listing' => 'listings#listing_interview', as: 'listing'
  get 'listing-inner' => 'listings#listing_inner', as: 'listing_inner'
  get 'listing-approval' => 'listings#listing_approval', as: 'approval_page'
  get 'applicants/index'
  get 'landings/index', as: 'landing'
  get '/newhome', to: 'landings#newhome', as: 'newhome'
  get '/pricing', to: 'landings#pricing', as: 'pricing'
  post 'landings/requestdemo', to: "landings#request_demo"
  put 'update_approval_status' => 'listings#update_approval_status', as: 'update_approval'
  get "build_profile", to: "users#build_profile", as: 'build_profile', :format => false
  post "build_profile_update", to: "users#update_profile", as: 'update_profile', :format => false
  put "become_interviewer", to: "users#become_interviewer", as: 'become_interviewer', :format => false
  put "become_applicant", to: "users#become_applicant", as: 'become_applicant', :format => false
  get "profile", to: "users#profile", as: 'user_profile', :format => false
  get "application_timeline", to: "users#application_timeline", as: 'user_timeline', :format => false
  get "dashboard/account", to: "users#account", as: 'user_account', :format => false
  post "dashboard/account", to: "users#account", as: 'user_account_put'
  get "dashboard/check_password", to: "users#check_password", as: 'check_password'
  get "dashboard/interviews", to: "users#interviews", as: 'user_interviews', :format => false
  get 'demo_login' , to: "users#user_demo_login", as: 'user_demo_login'
  get 'demo_in' , to: "users#trigger_login", as: 'trigger_login'
  get 'contact', to: "landings#contact", as: 'contact'
  get 'payment_test', to: "payment#payment_test", as: 'payment_test'
  get 'payment_test_url', to: "payment#payment_test_callback",  as: 'payment_test_callbadk'
  get 'payment_test_submit', to: "payment#payment_test_submit", as: 'payment_test_submit'

  put 'update_education', to: "users#update_education", as: 'update_education'
  put 'update_experience', to: "users#update_experience", as: 'update_experience'
  put 'update_skills', to: "users#update_skills", as: 'update_skills'
  put 'update_user_details', to: "users#update_user_details", as: 'update_user_details'
  get 'retrieve_education', to: "users#retrieve_education", as: 'retrieve_education'
  delete 'delete_education', to: "users#delete_education", as: 'delete_education'

  post "update_account_profile", to: "users#update_account_profile", as: "update_account_profile"
  post "update_account_skill", to: "users#update_account_skill", as: "update_account_skill"  

  get "check_if_user_exist", to: "users#check_if_user_exist", as: "check_if_user_exist"
  post "login_sign_up", to: "users#login_sign_up", as: "login_sign_up"

  # post request for applicant data
  post 'applicants/' => 'applicants#index'
  post 'applicants/question' => 'applicants#question'
  post 'applicants/submit_video' => 'applicants#submit_video'
  post 'applicants/upload_file' => 'applicants#upload_file'


  %w( validate_interview validate_email ).each do |action|
    get  action => 'applicants#'+action
  end

  get "check_subdomain", to: "companies#check_subdomain"

  # this is assigning device controllers for user(s)
  devise_for :users, controllers: {invitations: 'users/invitations', registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]


  # error handling routes, this will , pass the code to controller error and action show
  %w( 404 422 500 ).each do |code|
    get code, :to => "landings#errors", :code => code
  end



  # Nested Company Resources
  resources :companies do
    #post 'send_invite_mail', on: :collection
    #get "interview_reminder", to: "companies#interview_reminder"
    post "add_collaborators", to: "companies#add_collaborators"
    delete "remove_collaborator", to: "companies#remove_collaborator"
    put "transfer_ownership", to: "companies#transfer_ownership"
    get "edit_preview", to: "companies#edit_preview"
    post "edit_preview", to: "companies#edit_preview"
    get "all_interview", to: "companies#all_interview"
    get "preview", to: "companies#preview"
    get "card_preview", to: "companies#card_preview", as: 'card_preview'
    get "talent", to: "companies#search_talent", as: "talent"
    get "talent/:id", to: "companies#show_talent", as: "show_talent"
    get "organization_members", to: "companies#organization_members", as: "organization_members"

    resources :groups do
       get 'show_group_emails', on: :member
       resources :bulks do
          post 'import', on: :collection
      end
    end

    resources :interviews do
      post 'send_invite_mail', on: :collection
      get "reminder", to: "interviews#reminder"
      get "sms_reminder", to: "interviews#sms_reminder"
      get "double_reminder", to: "interviews#double_reminder"
      get "mass", to: "interviews#mass_notify"
      get "analytics", to: "interviews#analytics"
      get "single", to: "interviews#single_interview_submissions"
      get "returnTextFileApi", to: "interviews#returnTextFileApi"
      get "filtered_single_interview", to: "interviews#filtered_single_interview"
      put "change_status", to: "interviews#change_status"
      # get "shortlist", to: "interviews#shortlist"
      # get "reject", to: "interviews#reject"
      get "unfinish_submission", to: "interviews#unfinish_submission" 
      get "export_details", to: "submissions#export",  as: 'export_submissions'
      get "shortlist", to: "submissions#shortlist"
      get "reject", to: "submissions#reject"
    end

  end


  get 'users/auth/linkedin/callback', to: 'oauths#callback_linkedin', as: 'oauth_callback_linked'
  get 'users/auth/facebook/callback', to: 'oauths#callback'
  get 'users/auth/failure', to: 'oauths#failure', as: 'oauth_failure'
  # checking if the subdomain is available, if yes to to route
  # if not route back to rool url
  get '/' => 'applicants#index', :constraints => CustomDomainConstraint

  constraints(CustomDomainConstraint) do
     get '/' => 'applicants#index'
     get 'applicants/' => 'applicants#index'
     get 'applicants/:interview_token/' => 'applicants#index'

  end

  # You can have the root of your site routed with "root"
    root 'landings#index'

  #get 'users/auth/linkedin/callback' => 'users#createt'

# If you have the need for more deep customization,
# for instance to also allow "/sign_in" besides "/users/sign_in",
# all you need to do is to create your routes normally
# and wrap them in a devise_scope block in the router:
# This way, you tell Devise to use the scope :user when "/sign_in" is accessed. Notice devise_scope is also aliased as as in your router.


   devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    put    "update_notification"  => "users#update_notification"

    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end



# namespace and controller for api
namespace :api do
    namespace :v1 do
      get "token", to: "api#token"
      put "send_invitation", to: "api#send_invitation"

    end
  end

end

app/controllers/companies_controller.rb
require 'slack-notifier'
class CompaniesController < ApplicationController
	layout 'user_dashboard'
	before_action :authenticate_user!, :except => [:organization_members]
    before_filter :set_up_user, :except => [:organization_members]
    before_filter :set_up_company, :except => [:new, :create, :check_subdomain, :organization_members]



	def show
        if params[:from_notification].present?
            @user.update_attributes(last_company: @company.id)
        end
        @user_status = JointUserCompany.find_by(user_id: @user.id, company_id: @company.id)
        @sigin_in_count = current_user.sign_in_count.to_s
        @all_interview = @company.interviews
	end

	def new
        @unique_to_p = false
        @profile_page = true
        render  :layout => 'wizard'
	end


    def preview

    end

    def card_preview

    end

    def search_talent
            @sure_applicants = User.where(status:0)
            @unsure_applicants = User.where(status:nil)
            @applicants = @sure_applicants.merge(@unsure_applicants)
            @search_category = ['Skill', 'Discipline', 'Grade', 'City', 'School', 'Qualification']
     if  params[:search].present? && params[:category].present? && !params[:search2].present? && !params[:search3].present?
            @query = params[:search]
            #@field = assign_field(params[:category])
            @talent = @applicants.where("lower(#{params[:category]}) LIKE ?", "%#{params[:search].downcase}%").paginate(:page => params[:page], :per_page => 12)
            elsif params[:search2].present? && params[:category2].present? && !params[:search].present? && !params[:search3].present?
                @query = params[:search2]
                #@field = assign_field(params[:category])
                @talent = @applicants.where("lower(#{params[:category2]}) LIKE ?", "%#{params[:search2].downcase}%").paginate(:page => params[:page], :per_page => 12)
            elsif params[:search3].present? && params[:category3].present? && !params[:search].present? && !params[:search2].present?
                @query = params[:search3]
                #@field = assign_field(params[:category])
                @talent = @applicants.where("lower(#{params[:category3]}) LIKE ?", "%#{params[:search3].downcase}%").paginate(:page => params[:page], :per_page => 12)
            elsif params[:search].present? && params[:category].present? && params[:search2].present? && params[:category2].present? && !params[:search3].present?
                @query = params[:search3]
                #@field = assign_field(params[:category])
                @talent = @applicants.where("lower(#{params[:category]}) LIKE ?", "%#{params[:search].downcase}%").where("lower(#{params[:category2]}) LIKE ?", "%#{params[:search2].downcase}%").paginate(:page => params[:page], :per_page => 12)
            elsif params[:search].present? && params[:category].present? && params[:search3].present? && params[:category3].present? && !params[:search2].present?
                @query = params[:search3]
                #@field = assign_field(params[:category])
                @talent = @applicants.where("lower(#{params[:category]}) LIKE ?", "%#{params[:search].downcase}%").where("lower(#{params[:category3]}) LIKE ?", "%#{params[:search3].downcase}%").paginate(:page => params[:page], :per_page => 12)

           elsif params[:search2].present? && params[:category2].present? && params[:search3].present? && params[:category3].present? && !params[:search].present?
                @query = params[:search3]
                #@field = assign_field(params[:category])
                @talent = @applicants.where("lower(#{params[:category2]}) LIKE ?", "%#{params[:search2].downcase}%").where("lower(#{params[:category3]}) LIKE ?", "%#{params[:search3].downcase}%").paginate(:page => params[:page], :per_page => 12)
          elsif params[:search].present? && params[:category].present? && params[:search2].present? && params[:category2].present? && params[:search3].present? && params[:category3].present?
                @query = params[:search3]
                #@field = assign_field(params[:category])
                @talent = @applicants.where("lower(#{params[:category]}) LIKE ?", "%#{params[:search].downcase}%").where("lower(#{params[:category2]}) LIKE ?", "%#{params[:search2].downcase}%").where("lower(#{params[:category3]}) LIKE ?", "%#{params[:search3].downcase}%").paginate(:page => params[:page], :per_page => 12)
         elsif  !params[:search].present? && !params[:search2].present? && !params[:search3].present?
                @talent = @applicants.order("RANDOM()").paginate(:page => params[:page], :per_page => 12)

     end
          render :layout => 'single_interview_submissions'
    end




    def assign_field (val)
        if val == "Skill"
            return "skill"
        elsif val == "Field"
             return "field_of_study"
         elsif val == "Grade"
             return "grade"
         elsif val == "Location"
             return "city"
         elsif val == "School"
             return "school"
        end
    end

    def show_talent
        @profile_page = true
        @logo_off = false
    end

    def organization_members
        company = Company.friendly.find(params[:company_id] || params[:id])
        render :json => {msg: "" , data: JSON.parse(company.users.to_json(:only => [:email, :name ])) }
    end


    def edit_preview
        if params[:properties].present?
            @company.update_attributes(company_properties)
        end
         @editable = "true"
        render  :layout => 'applicants', :template => 'applicants/index'
    end


    def all_interview
        @all_interview = @company.interviews
    end





    def add_collaborators
        # after this, loop through everyother user and send notification and email to them
            collaborator_list = JSON.parse(params[:collaborators_list])
            collaborator_list.each do | collborator |

                email = collborator["email"]
                status = collborator["status"]

                # check if user exist,  this will be used for 
                if User.exists?(email: email)
                    send_mail = true 
                else
                    send_mail = false 
                end

                
                # invite user with device
                user = User.invite!({:email => email }, current_user)

                # check if  user exit in the company
                result = JointUserCompany.find_by(user_id: user.id, company_id: @company.id)

                if result.nil?
                    # send notification
                    if send_mail
                        self.send_notification(user.id, 2 , params[:user_id], @company.name)
                    end

                    # add user to joint_user_company model
                    one_collaborator = JointUserCompany.new(status: status, user_id: user.id, company_id: @company.id)
                    one_collaborator.save

                end
            end

        redirect_to edit_company_path(params[:company_id] || params[:id])
    end


    #remove 
    # do to, kindly change this to find by user and company so that no one can just passed a
    # delete call to ajax to delete any user's collaboration
    def remove_collaborator
        user_company = JointUserCompany.find(params[:user_company_id])
        if !user_company.destroy
           render plain: "failure"
        else
          # send notification 
          self.send_notification(user_company.user.id, 4 , @user.id, @company.name)
          render plain: "success"
        end
    end

    # transfer ownership
    def transfer_ownership
         current_owner = JointUserCompany.find(params[:current_owner])
         new_owner = JointUserCompany.find(params[:new_owner])
        if current_owner.update_attributes(status: 1) && new_owner.update_attributes(status: 0)
             # send notification 
            self.send_notification(new_owner.user.id, 5 , current_owner.user.id, @company.name)
            redirect_to edit_company_path(@company)
        else

        end
    end



    def check_subdomain
        if  Company.exists?(subdomain: params[:subdomain])
          render plain: "yes"
        else
          render plain: "no"
        end
    end



    def edit
        @user_company = JointUserCompany.find_by(user_id: @user.id, company_id: @company.id) 
        @collborators = @company.joint_user_companies
        @user_status = @user_company.status
    end


    def update  
        @company.update_attributes(create_company_params)
        redirect_to edit_company_path
    end

	def create
		company = Company.new(create_company_params)
		 # return api_error(status: 422, errors: user.errors.full_messages) unless user.valid?
        if company.save
        	#  create add the user as the super admin and ower to company
        	owner = JointUserCompany.new(status:0, user_id: params[:user_id], company_id: company.id)
        	owner.save


        	# after this, loop through everyother user and send notification and email to them
        	collaborator_list = JSON.parse(params[:collaborators_list])
        	collaborator_list.each do | collborator |

        		email = collborator["email"]
        		status = collborator["status"]

        		# invite user with device
        		user = User.invite!({:email => email }, current_user)

                 # check if  user exit in the company
                result = JointUserCompany.find_by(user_id: user.id, company_id: company.id)
                if result.nil?

                    # send notification
                    self.send_notification(user.id, 2 ,params[:user_id], company.name)

                    # add user to joint_user_company model
            		one_collaborator = JointUserCompany.new(status: status, user_id: user.id, company_id: company.id)
                    one_collaborator.save
                end
            end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_sidebar.html.erb
<div class="sidebar-wrapper">

            <div class="logo align">
                <% if @company.logo.file.nil? %>
                  <%= image_tag('dqlg.png') %>
                <% else %>
                  <img src="<%= @company.logo.url %>" style="height: 68px;"  />
                <% end %>

             </div>



            <ul class="nav">
                <li id="step1">
                    <%= link_to new_company_interview_path(params[:company_id] || params[:id]) do %>
                   <button  type="button" class="button">Create interview</button>

                   <% end %>
                </li>

                <li id="step2" class="<%= (params[:c] == "1") ? "active": "" %>">
                    <%= link_to company_path(params[:company_id] || params[:id], c: 1) do %>
                        <i class="ti-home"></i>
                        <p>Interviews</p>
                    <% end %>
                </li>

                <%# <li id="step2" class="<%= (params[:c] == "2") ? "active": "" %1>"> %>
                <%#     <%= link_to company_talent_path(params[:company_id] || params[:id], c: 2) do %1> %>
                <%#         <i class="ti-search"></i> %>
                <%#         <p>Discover Talent</p> %>
                <%#     <% end %1> %>
                <%# </li> %>


                <% if !@interview.nil? && @new_interview.nil? %>
                <li id="step4" class="<%= (params[:c] == "3") ? "active": "" %>">
                    <%= link_to company_interview_filtered_single_interview_path(params[:company_id] || params[:id], c: 3, status: 0, interview_id: @interview.slug) do %>
                        <i class="ti-check-box"></i>
                        <p>Shortlisted</p>
                    <% end %>

                </li>
                <li id="step5" class="<%= (params[:c] == "4") ? "active": "" %>">
                    <%= link_to company_interview_filtered_single_interview_path(params[:company_id] || params[:id], c: 4, status: 1, interview_id: @interview.slug) do %>
                        <i class="ti-pencil-alt"></i>
                        <p>Pending</p>
                    <% end %>

                </li>
                <li id="step6" class="<%= (params[:c] == "5") ? "active": "" %> ">
                    <%= link_to company_interview_filtered_single_interview_path(params[:company_id] || params[:id], c: 5, status: 2, interview_id: @interview.slug) do %>
                        <i class="ti-trash"></i>
                        <p>Declined</p>
                    <% end %>

                </li>
                <!-- <li id="step6" class="<%= (params[:c] == "6") ? "active": "" %> ">
                    <%= link_to company_interview_unfinish_submission_path(params[:company_id] || params[:id], c: 6, interview_id: @interview.slug) do %>
                        <i class="ti-control-pause"></i>
                        <p>Unfinished</p>
                    <% end %>
                </li>   -->
                <li id="step6" class="<%= (params[:c] == "6") ? "active": "" %> ">
                    <%= link_to  company_interview_export_submissions_path(params[:company_id] || params[:id], c: 6, interview_id: @interview.slug) do %>
                        <i class="ti-export"></i>
                        <p>Export Details</p>
                    <% end %>

                </li>

                 <li id="step10" class="<%= (params[:c] == "7") ? "active": "" %> ">
                    <%= link_to "#" do %>
                        <i class="ti-bell"></i>
                        <p>Send reminders</p>
                        <% end %>
                 </li>

                  <li id="step11" class="<%= (params[:c] == "8") ? "active": "" %> ">
                    <%= link_to   company_interview_analytics_path(params[:company_id] || params[:id], c: 8, interview_id: @interview.slug) do %>
                        <i class="ti-bar-chart"></i>
                        <p>Analytics</p>
                    <% end %>
                 </li>
                <% end %>
            </ul>

    	</div>
    </div>


<!-- send reminder  -->
<div class="modal fade" id="reminder-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h5 class="modal-title" >  Send Reminder by: </h5>
          </div>
              <div class="modal-body">
                <select id = "remoption" class='btn box-shape' name ="new_owner" >
              <option value='1'> SMS </option>
              <option value='2'> EMAIL </option>
              <option value='3'> SMS&EMAIL</option>
                </select>
              </div>
          <div class="modal-footer">
            <button type="button" class="btn box-shape" data-dismiss="modal"> Cancel </button>
            <button id="reminder-continue" type="submit"  class="btn box-shape"> Send </button>
          </div>

    </div>
  </div>
</div>



<script >

 $("#step10").click(function(){
    $("#reminder-modal").modal();
 });

    var mev =  $("#reminder-modal").find(".modal-footer");
    mev.find("button#reminder-continue").click(function(event){
    $("#reminder-modal").modal('hide');
    var med = $("#reminder-modal").find(".modal-body");
    var type = med.find("option:selected");
    var typeValue = type.get(0).value;
    if (typeValue == "1"){
      var type = "Are you sure to SEND REMINDERS? SMS messages will be sent to Candidates who have not completed  the interview @ 4 naira/sms";
    } else if(typeValue == "2"){
      var type = "Are you sure to SEND REMINDERS ? Email Will be sent to the Candidates who have  not completed the interview";
    }else{
      var type = "Are you sure to SEND REMINDERS? SMS and Email messages will be sent to Candidates who have not completed  the interview @ 4 naira/SMS";
    }
    if (confirm(type) == true){
    var id_input = $("#interview_id");
    var id = id_input.attr("value");
    var url;
    if (typeValue == "1"){
      url = "/companies/<%= @company.slug %>/interviews/"+id+"/sms_reminder";
    } else if (typeValue == "2")
    url = "/companies/<%= @company.slug %>/interviews/"+id+"/reminder";
    else {
      url = "/companies/<%= @company.slug %>/interviews/"+id+"/double_reminder";
    }
     $.ajax({
       type: 'GET',
       url: url
     });

  }


  else{
    event.preventDefault();
    }

    });

 $("#step10").click(function(){
    $("#reminder-modal").modal();
 });

 $("#reminder-continue").click(function(){
     $("#reminder-modal").modal('hide');
 // the logic of sending the reminder

 });


</script>

app/views/companies/_when_empty.html.erb
<div class="content">

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div >
                    <div class="row sharing-area text-center">
                        <br> <br> <br> <br>                         
                        <h3>Welcome to your <%= @company.name %>  dashboard!</h3>
                        <h5> Start by creating an interview </h5>

                     <%= link_to new_company_interview_path(params[:company_id] || params[:id]) do %>
                        <button  type="button" class="btn btn-raised btn-twitter">Create an interview</button>
                    <% end %>


                        <br> <br> <br> <br><br> <br>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/companies/card_preview.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="success">

<!-- TODO Add Sidebar Panel -->
     <%= render partial: "companies/sidebar" %>
    <div class="main-panel">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
   
        
                
          

 </div>
</div>
</div>

app/views/companies/show.html.erb
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="danger">

<!-- TODO Add Sidebar Panel -->
    <%= render partial: "sidebar" %>
    <div class="main-panel ">
<!-- TODO Add Navbar Panel -->
    <%= render partial: "users/navbar" %>
        <div class="content card-start ">
            <div class="container-fluid">


               <!-- when empty -->
            <% if @all_interview.length == 0  %>
             <%= render partial: "when_empty" %>
            <% end %>

                <div class="row" >

                  <% @all_interview.each do |interview| %>
                  <% unfinish_submission = interview.submissions.where("current_no < ?", 500) %>
                  <% submissions = interview.submissions.where(current_no: 500, status:nil) %>
                  <% questions = interview.questions.length%>
                  <% shortlisted = Submission.where(interview_id:interview.id).where(status:0).length %>
                  <% rejected = Submission.where(interview_id:interview.id).where(status:2).length %>
                      <div class="col-md-4">
                          <div class="img-responsive card box-shape">

                              <div class="content">
                                    <div class="row">
                                      <div class="col-xs-8">
                                        <div class="stats">
                                         Interview token: <%= interview.interview_token %>
                                        </div>
                                      </div>
                                      <div class="col-xs-4">
                                        <a href="<%= company_interview_path(id: interview.slug, company_id: @company.id) %>" rel="tooltip"  class="btn btn-info btn-simple " data-original-title="View Interview">
                                            <i class="ti-image"></i>
                                        </a>  |
                                        <a href="<%= edit_company_interview_path(id: interview.slug, company_id: @company.id) %>" rel="tooltip" class="btn btn-success btn-simple" data-original-title="Edit Interview">
                                            <i class="ti-pencil"></i>
                                        </a>
                                      </div>
                                    </div>
                                        <hr>

                                      <div class="text-center numbers-1">

                                <a  href= "<%= company_interview_single_path(company_id: @company.slug, interview_id: interview.slug ) %>" >
                                         <p><%= truncate( interview.title, :length => 35) %> </p>
                                          <%= submissions.length %>
                                        <br>
                                </a>
                                      </div>
                                      <hr>
                                  <div class="chart-legend">
                                      <div class="row">
                                          <div class="col-md-4 col-xs-4">
                                            <div class="icon-big icon-warning text-center" style="
    font-size: 1em;">
                                               Question<i class="ti-help"></i><hr>
                                               <h4><%= questions %></h4>
                                            </div>
                                          </div>
                                          <vr />
                                          <div class="col-md-4 col-xs-4">
                                            <div class="icon-big icon-success text-center" style="
    font-size: 1em;">
<%= link_to company_interview_filtered_single_interview_path(params[:company_id] || params[:id], c: 3, status: 0, interview_id: interview.slug), class:"icon-success" do %>

                                               Shortlisted<i class="ti-check"></i><hr>
                                               <h4><%= shortlisted %></h4>
                                            <% end %>

                                            </div>
                                          </div>
                                          <div class="col-md-4 col-xs-4">
                                            <div class="icon-big icon-danger text-center" style="
    font-size: 1em;">

                    <%= link_to company_interview_filtered_single_interview_path(params[:company_id] || params[:id], c: 5, status: 2, interview_id: interview.slug), class:"icon-danger" do %>
                       
                                               Declined<i class="ti-close"></i><hr>
                                               <h4><%= rejected %><h4>
                    <% end %>
                                            </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>                  
                          </div>
                      </div>
  
                  <% end %>
                </div>

            </div>
        </div>

    </div>
    </div>
</div>